version: '3.12'

services:
  web:
    build: .
    command: ["sh", "-c", "python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - .:/mysite
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: 'mysite'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'

volumes:
  postgres_data:
