# Generated by Django 5.0.6 on 2024-05-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_customuser_options_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
