# Generated by Django 5.0.6 on 2024-05-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
