# Generated by Django 5.0.6 on 2024-06-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_customuser_address_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_files/')),
                ('text', models.TextField()),
            ],
        ),
    ]
