# Generated by Django 5.0.6 on 2024-06-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_audiotext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioText',
        ),
    ]
