# Generated by Django 5.0.6 on 2024-06-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_otpdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamingLaptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=150)),
                ('ram', models.IntegerField()),
                ('Storage', models.IntegerField()),
                ('storage_type', models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD')], max_length=50)),
                ('gpu', models.CharField(max_length=150)),
                ('screen', models.FloatField()),
                ('touch', models.BooleanField()),
                ('price', models.FloatField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
