# Generated by Django 5.0.6 on 2024-06-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_gaminglaptop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GamingLaptop',
        ),
    ]
