# Generated by Django 5.0.6 on 2024-06-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0012_delete_gaminglaptop'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_portal_user',
            field=models.BooleanField(default=False),
        ),
    ]
