# Generated by Django 4.2.13 on 2024-06-10 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GamingLaptop',
            new_name='Laptops',
        ),
    ]
