# Generated by Django 4.2.13 on 2024-06-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_rename_gaminglaptop_laptops'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laptops',
            new_name='Laptop',
        ),
    ]
