# Generated by Django 4.2.13 on 2024-06-14 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0005_alter_laptop_cpu_alter_laptop_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
