# Generated by Django 4.2.13 on 2024-06-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('case_materal', models.CharField(max_length=100)),
                ('strap_material', models.CharField(max_length=100)),
                ('movement_type', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('Quartz', 'Quartz')], verbose_name=50)),
                ('water_resistance', models.IntegerField(blank=True, null=True)),
                ('case_diameter', models.IntegerField(blank=True, null=True)),
                ('case_thickness', models.IntegerField(blank=True, null=True)),
                ('bandwidth', models.IntegerField(blank=True, null=True)),
                ('dial_color', models.CharField(max_length=150)),
                ('crystal_material', models.CharField(max_length=100)),
                ('complications', models.CharField(blank=True, max_length=255, null=True)),
                ('power_reserve', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
