# Generated by Django 4.2.13 on 2024-06-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='power_reserve',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
