# Generated by Django 4.2.13 on 2024-06-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watches', '0002_alter_watch_power_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
