# Generated by Django 4.2.13 on 2024-06-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watches', '0003_alter_watch_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='bandwidth',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watch',
            name='case_diameter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watch',
            name='case_thickness',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='watch',
            name='complications',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='watch',
            name='model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='watch',
            name='power_reserve',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='watch',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='watch',
            name='water_resistance',
            field=models.IntegerField(),
        ),
    ]
