# Generated by Django 4.2.13 on 2024-06-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Watches', '0005_alter_watch_bandwidth_alter_watch_case_diameter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='case_materal',
            new_name='case_material',
        ),
    ]
