# Generated by Django 4.2.13 on 2024-06-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watches', '0006_rename_case_materal_watch_case_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='water_resistance',
            field=models.IntegerField(max_length=100),
        ),
    ]
