# Generated by Django 4.2.13 on 2024-06-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watches', '0007_alter_watch_water_resistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='water_resistance',
            field=models.CharField(max_length=100),
        ),
    ]
