# Generated by Django 4.2.13 on 2024-06-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watches', '0008_alter_watch_water_resistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='bandwidth',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='watch',
            name='case_diameter',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='watch',
            name='case_thickness',
            field=models.FloatField(),
        ),
    ]
