# Generated by Django 4.2.13 on 2024-06-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watches', '0009_alter_watch_bandwidth_alter_watch_case_diameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='price',
            field=models.FloatField(),
        ),
    ]
