# Generated by Django 4.2.13 on 2024-06-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watches', '0012_alter_watch_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
