# Generated by Django 4.2.13 on 2024-06-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watches', '0014_alter_watch_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watch',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='watch',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
