# Generated by Django 4.2.13 on 2024-06-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watches', '0015_alter_watch_options_watch_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='movement_type',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('Quartz', 'Quartz')], max_length=50),
        ),
    ]
