# Generated by Django 4.2.13 on 2024-06-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watches', '0016_alter_watch_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
