# Generated by Django 4.2.13 on 2024-06-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watches', '0017_alter_watch_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='price',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
