# Generated by Django 5.0.6 on 2024-06-18 10:02

import django.db.models.expressions
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watches', '0018_alter_watch_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(db_default=18)),
                ('count', models.IntegerField(default=10)),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('base', models.FloatField()),
                ('height', models.FloatField()),
                ('area', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('base'), '*', models.F('height')), output_field=models.FloatField())),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
