# Generated by Django 5.0.6 on 2024-06-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watches', '0020_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='sport',
            field=models.CharField(choices=[('Martial Arts', [('judo', 'Judo'), ('karate', 'Karate')]), ('Racket', [('badminton', 'Badminton'), ('tennis', 'Tennis')]), ('unknown', 'Unknown')], null=True),
        ),
    ]
